apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-query
  template:
    metadata:
      labels:
        app: blog-query
    spec:
      containers:
      - name: blog-query
        image: ijanzz5621/blog-query:latest
        ports:
        - containerPort: 4002
