apiVersion: v1
kind: Service
metadata:
  name: blog-eventbus-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: blog-eventbus
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP