apiVersion: v1
kind: Service
metadata:
  name: blog-posts-service
spec:
  type: NodePort
  selector:
    app: blog-posts
  ports:
    - name: blog-posts
      protocol: TCP
      port: 4000 # port of this service
      targetPort: 4000 # port for the pod
