apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-moderation
  template:
    metadata:
      labels:
        app: blog-moderation
    spec:
      containers:
      - name: blog-moderation
        image: ijanzz5621/blog-moderation:latest
        ports:
        - containerPort: 40003