apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-comments
  template:
    metadata:
      labels:
        app: blog-comments
    spec:
      containers:
      - name: blog-comments
        image: ijanzz5621/blog-comments:latest
        ports:
        - containerPort: 5000
