apiVersion: v1
kind: Service
metadata:
  name: blog-moderation-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: blog-moderation
  ports:
  - port: 4003
    targetPort: 4003
    protocol: TCP