apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-client
  template:
    metadata:
      labels:
        app: blog-client
    spec:
      containers:
      - name: blog-client
        image: ijanzz5621/blog-client:latest
        ports:
        - containerPort: 3000