apiVersion: v1
kind: Service
metadata:
  name: blog-client-service
spec:
  type: NodePort
  selector:
    app: blog-client
  ports:
    - name: blog-client
      protocol: TCP
      port: 3000 # port of this service
      targetPort: 3000 # port for the pod
