apiVersion: v1
kind: Service
metadata:
  name: blog-comments-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: blog-comments
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP